version: '3'
services:
  arangodb:
    container_name: "arangodb"
    image: arangodb:latest
    environment:
      - ARANGO_ROOT_PASSWORD=pwd4arango
    volumes:
      - ./arango-data:/var/lib/arangodb3
    ports:
      - 8529:8529